#!/usr/bin/env bash
# helm-sync.sh — copy kubebuilder-generated manifests from config/** into the
# Helm charts so the charts never drift from the controller-gen markers.
#
# The generated files (config/crd/bases/*, config/rbac/role.yaml,
# config/webhook/manifests.yaml) remain the single source of truth. This script
# is a pure, deterministic copy: re-running it after `make manifests generate`
# produces byte-identical output, so CI can assert `git diff --exit-code` on the
# charts to catch a stale sync.
#
#   - CRD  -> charts/kube-headroom-crds/templates/headroomconfig-crd.yaml    (the
#            standalone CRD chart), and, gated on .Values.crds.install, into
#            charts/kube-headroom/templates/crd.yaml (a one-shot install of the
#            operator that also lays down the CRD). Both are the generated CRD
#            verbatim with only Helm directives injected for the
#            resource-policy: keep annotation and chart labels — no YAML
#            round-trip, so the CEL schema is copied untouched.
#   - RBAC rules and webhook config are copied verbatim into the operator
#     chart's files/ dir; their templates load them with .Files.Get so the
#     generated payload stays authoritative while names/namespaces/labels are
#     templated.
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${repo_root}"

crd_src="config/crd/bases/kube-headroom.dev_headroomconfigs.yaml"
role_src="config/rbac/role.yaml"
webhook_src="config/webhook/manifests.yaml"

crds_chart="charts/kube-headroom-crds"
operator_chart="charts/kube-headroom"

for f in "${crd_src}" "${role_src}" "${webhook_src}"; do
	if [ ! -f "${f}" ]; then
		echo "helm-sync: missing generated file '${f}'. Run 'make manifests generate' first." >&2
		exit 1
	fi
done

# emit_crd_template SRC DEST LABELS_INCLUDE [WRAP_CONDITION]
# Copies the generated CRD verbatim, injecting after the controller-gen version
# annotation: a conditional helm.sh/resource-policy: keep annotation and chart
# labels (via LABELS_INCLUDE). If WRAP_CONDITION is given, the whole document is
# wrapped in `{{- if <cond> }} ... {{- end }}`. The schema body is never touched.
emit_crd_template() {
	local src="$1" dest="$2" labels_include="$3" wrap="${4:-}"
	mkdir -p "$(dirname "${dest}")"
	{
		if [ -n "${wrap}" ]; then
			echo "{{- if ${wrap} }}"
		fi
		echo "# Generated by 'make helm-sync' from ${src} — DO NOT EDIT."
		echo "# Source of truth: the kubebuilder markers. Regenerate with 'make manifests generate helm-sync'."
		awk -v labels="${labels_include}" '
		{ print }
		/^    controller-gen\.kubebuilder\.io\/version:/ {
			print "    {{- if .Values.keep }}"
			print "    helm.sh/resource-policy: keep"
			print "    {{- end }}"
			print "  labels:"
			print "    {{- include \"" labels "\" . | nindent 4 }}"
		}
		' "${src}"
		if [ -n "${wrap}" ]; then
			echo "{{- end }}"
		fi
	} >"${dest}"
}

# --- CRD chart: keep gated on .Values.keep (default true). ------------------
emit_crd_template "${crd_src}" \
	"${crds_chart}/templates/headroomconfig-crd.yaml" \
	"kube-headroom-crds.labels"

# --- Operator chart: only rendered when .Values.crds.install is set. In that
# path .Values.keep is unset, so the `{{- if .Values.keep }}` guard is replaced
# below with the operator chart's own crds.keep gate (default true).
emit_crd_template "${crd_src}" \
	"${operator_chart}/templates/crd.yaml" \
	"kube-headroom.labels" \
	".Values.crds.install"
# Retarget the keep guard from the CRD chart's `.Values.keep` to the operator
# chart's `.Values.crds.keep` (default true).
sed -i.bak 's/{{- if \.Values\.keep }}/{{- if (default true .Values.crds.keep) }}/' \
	"${operator_chart}/templates/crd.yaml"
rm -f "${operator_chart}/templates/crd.yaml.bak"

# --- Operator chart data files ---------------------------------------------
# Copied verbatim; the chart templates wrap them with name/label/namespace/toggle
# templating via .Files.Get.
mkdir -p "${operator_chart}/files"
{
	echo "# Generated by 'make helm-sync' from ${role_src} — DO NOT EDIT."
	cat "${role_src}"
} >"${operator_chart}/files/manager-role.yaml"

{
	echo "# Generated by 'make helm-sync' from ${webhook_src} — DO NOT EDIT."
	cat "${webhook_src}"
} >"${operator_chart}/files/webhook-manifests.yaml"

echo "helm-sync: synced CRD, RBAC rules, and webhook config into charts/."
