{{- if .Values.podDisruptionBudget.enable }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "kube-headroom.fullname" . }}-controller-manager
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-headroom.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "kube-headroom.selectorLabels" . | nindent 6 }}
{{- end }}
