apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-headroom.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-headroom.labels" . | nindent 4 }}
{{- with .Values.imagePullSecrets }}
imagePullSecrets:
  {{- toYaml . | nindent 2 }}
{{- end }}
